language: node_js
node_js:
- node
jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      && rm -rf ./coverage
  - stage: Stryker
    node_js: node
    script: npm test
env:
  global:
  - secure: iIYShjpHubPZUUbNWkLtpqFDjNDsFA1qcCuWBelmTLljErhmH9IUWl/vaJs/hDz4GMGhEVNQd/dXE37uS4Ny0ivBKuAdL12qHXZ1S3QP7bLvtjed0cvvzhufcGroEheGVBx/qxjd2hTr0YhbBngj692AQkSPhCibqR7LfNQbgfuneOk0sO71N0nwzuOpOs34AUXJ76tMm4039I9uhUsJ8Cbi565B4AMDAVKTPegQPF1K30xzf4TCHkK5ZURckqxlduqf0FR2HjXEbfBsAMFBAX/QGWZ9G3EO59YfS+/mgispsCqT7jTWwSX76qhjshuJocSkjncxOnbD3Dm8BO+QWHiOMH3kvsFYfmvAg3W6Hivy8QKImyQ9Zk0LoV/GPETyreOam2jlJOQgiykO7OpbEcTwfXCDteM/SrGoRjrvlK/Uv0USg/lUPs5xCoNLwpp4V8+SjvQmGx/oNb8382cgMDKQgshsL4uI7nNhs7SmA3VWoLq5/VYeFcmUTffTo1HyVumOjpWgioeAjWIyo5PV1t3f3/zCIf2oREc3vClEcPC/cvgHCJBqCv2yu9Bu5zG6EmHPPuIj39wQ+A6vrZ4B33supvRljVlyH5QETA8F7tTPusWQmO4HSqiWQJ2qA7nCarpV/PRCtjgtO9j+inb28w+t4LvGVDSFOAm4XBVRvhE=
  - secure: cewauBGZ84ViK3VIQGmBnnYc5cr0ELEFrb/LTXwFUmqZuIbmqdcjsDWICERjLLOa2Bh1G6QuKIsK33/e5eHtHUQ78wAGEEJ3hnlsx07hpFdR4pVhR8DFpceZmszlxOh6vUpJW++KZ8eHv71ft66UPOWVIoBtkHdgrKvTwjlHQOAYoFFunZhR7Bs5hGi9qArNk/IL5c7XYb46PzcP5dS2DsAEBNVMoBw61btd6BEiob7aaU16NjrbAgi33VpRyIvmPO2PAs3krc5Y/XiC57Gl1G0CzNpRIrTnxxx64bQyllFC9cZum2ggM4Ib0HdfFLnACJhSVZvpvKWq0c3kGMKnjm+tOVghw78niOeJzAIiXA9oDFjTg8X6wC86v4rert/9oBAF7gWeJRnIbGMCSqqZNIraleUnPfSviiBlBXDfSDcekWoK/qMXdHOK2z9kHCCsAmn06nXWhMfzSWPJUxPdlsAeBv/ERR2dI0R+JDIUIaRDkmfDTBi1AMfXIdvudHVtFMGPNJ653cQnYrsBfdrYX6de3XqKCdFUy+8vKzfRiTuF/DwdVNjKJiquzhoJSZzHI9YFt+D4Jo5mo4oYFL4dgStjl6gGvYpTgk4I24ATTNoo6KtO1LS0ziouuZwKXa6InnNnIJC8pGqQ5fvzhvYEXIpISN31Zea48X031OqTmKY=
